# configuration/base.yaml
application: 
  port: 8000
  hmac_secret: "whatever-it-is-that-rocks-your-boat-then-that-is-your-gig-random-words-until-i-get-success"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 1000
